### ISSUE TITLE
Error: The Expo SDK requires Expo to run.

### ISSUE THREAD

**Issue by Mr-Ingram** [thomaswangio/react-native-gradient-buttons#13]
After I installed the package for Android and ran the program, I get this error. To try to fix this, I ran `npm install expo`, but this did not do anything. How do I fix this problem?

**Comment by thomaswangio** [comment]
Hm @Mr-Ingram I have to do more investigating on this, but won't be able to get to it for at least a couple weeks. I will be getting more into Expo development because they just announced it can be used in any React Native project: https://twitter.com/expo/status/1101245001042878464. 

In the meantime, the library is very simple so if you have time I'd welcome a PR.

**Comment by thomaswangio** [comment]
This issue has been resolved thanks to @braytonstafford, I made a few adjustments but everything should be working now without Expo as a dependency. Only need to include react and react-native!

see https://github.com/thomaswangio/auth-screens for updated example project using new version v.2.0.1

cc @Mr-Ingram
