### ISSUE TITLE
Dependency with Expo

### ISSUE THREAD

**Issue by hansen94** [thomaswangio/react-native-gradient-buttons#8]
can this library be used outside of Expo? 
I tried installing with npm in a react-native project but i am getting this error: 
![simulator screen shot - iphone x - 2018-12-21 at 18 02 47](https://user-images.githubusercontent.com/8460050/50339701-a4ac8800-054a-11e9-88cd-0ab2090cd545.png)

Am i doing something wrong? 
Thank you so much

**Comment by thomaswangio** [comment]
Hey @hansen94, unfortunately not yet. For this to work, we'd need to refactor to use ExpoKit as a dependency and then have necessary Pods + Android dependencies since they handle the linear gradients and haptic feedback differently. Or just use pure native dependencies without ExpoKit.

Definitely would be a useful feature, though, will investigate when I have some time. Help obviously welcome :)

**Comment by hansen94** [comment]
Oh that's too bad. This is a useful library.
Well, i guess i'll try my luck with react-native-linear-gradient. 
Thank you so much for your reply.

**Comment by thomaswangio** [comment]
Hey @hansen94 we can use this package in any React Native project now thanks to @braytonstafford and Expo Unimodules! Upgrade to v.2.0.1

https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331
